spring:
  profiles:
    active: dev
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.29:3306/hx-sq?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
code:
  author: lyc
  company: com.jiopeel  #公司名
  view:
    urlPrefix:
    suffix: .html  #生成模板的后缀
    path: F:\webspace\jiopeel-parent\jiopeel-admin-web\src\main\resources\templates\blog
  java:
    beanPath: D:\workspace\psims-create-sq\jiopeel-project\jiopeel-project-bean\src\main\java\com\jiopeel\project
    eventPath: D:\workspace\psims-create-sq\jiopeel-project\jiopeel-project-mc\src\main\java\com\jiopeel\project\event
    logicPath: D:\workspace\psims-create-sq\jiopeel-project\jiopeel-project-mc\src\main\java\com\jiopeel\project
#code:
#  author: lyc
#  company: com.jiopeel  #公司名
#  view:
#    suffix: .html  #生成模板的后缀
#    path: \Users\lyc\workspace\SpringbootDEMO\src\main\resources\templates\sys
#  java:
#    path: \Users\lyc\workspace\SpringbootDEMO\src\main\java\com\jiopeel\sys
